title: HANSASTEDT Maschinentechnik GmbH
email: vertriebnord@hansastedt.de
address:
    street: August-Bebel-Str.
    number: 4
    PLZ: 61184
    city: Karben
    country: Germany

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


navbar-pages:
    - page: index.html
      de: Startseite
    - page: about-us.html
      de: Ãœber uns
